[Profile]
profile_id = omadora
base_profile = fedora

[User Interface]
webui_web_engine = firefox
can_change_users = True
can_change_root = False
hidden_webui_pages =

[Storage]
default_scheme = BTRFS
btrfs_compression = zstd:1

[Network]
default_on_boot = FIRST_WIRED_WITH_LINK

[Localization]
use_geolocation = False

[Timezone]
geolocation_provider =
